CREATE TABLE IF NOT EXISTS area (
    id   BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS report (
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    area_id     BIGINT NOT NULL REFERENCES area(id),
    crowd_level VARCHAR(10) NOT NULL,   -- LOW | MEDIUM | FULL
    steward     VARCHAR(100),
    reported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alert (
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    area_id    BIGINT NOT NULL REFERENCES area(id),
    message    VARCHAR(255) NOT NULL,
    resolved   BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
